hadoop1:
    image: centos-hadoop
    hostname: hadoop1
    container_name: hadoop1
    ports: 
        - "5070:50070"
        - "8088:8088"
        - "1022:22"
        - "8000:8000"
    links:
        - hadoop2
        - hadoop3
        - hadoop4
        - hadoop5
  
hadoop2:
    image: centos-hadoop
    container_name: hadoop2
    hostname: hadoop2
    ports:
        - "5071:50070"
        - "8089:8088"
        - "1023:22"
hadoop3:
    image: centos-hadoop
    container_name: hadoop3
    hostname: hadoop3
  
hadoop4:
    image: centos-hadoop
    container_name: hadoop4
    hostname: hadoop4

hadoop5:
    image: centos-hadoop
    container_name: hadoop5
    hostname: hadoop5
